spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    include: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/todo
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level:
    org.hibernate.SQL: debug
