spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

todoUrl: http://localhost:8080/todos/